services:
   app:
      build: .
      env_file:
         - .env
      ports:
         - "8000:8000"
      healthcheck:
         test: [ "CMD", "gunicorn", "--help", "--exit-zero" ]

   nginx:
      image: nginx:latest
      ports:
         - "80:80"
      volumes:
         - ./nginx/kyle.conf:/etc/nginx/conf.d/kyle.conf:ro
         - ./app/static:/app/staticfiles:ro
      depends_on:
          app:
            condition: service_healthy

networks:
  default:
    driver: bridge
