services:
    app:
        build: .
        volumes:
             - ./app:/app
        depends_on:
             - db
        networks:
          - content_deriver

    db:
        image: postgres:16
        ports:
           - "5432:5432"
        env_file:
           - .env
        environment:
           POSTGRES_PASSWORD: ${ROOTPASS}
           POSTGRES_DB: ${DATABASE}
           POSTGRES_USER: ${DBUSER}
        volumes:
           - db_data:/var/lib/postgresql/data

        networks:
          - content_deriver

    nginx:
        image: nginx:latest
        ports:
           - "80:80"
        volumes:
           - ./nginx/default.conf:/etc/nginx/conf.d/app.conf:ro
        depends_on:
           - app
        networks:
          - content_deriver

volumes:
      db_data:

networks:
    content_deriver:
           driver: bridge
