name: CD

on:
   push:
      branches: [master]

jobs:
   deploy:
      needs: build
      runs-on: self-hosted
      steps:
         - name: Deploy to self hosted runner
           run: docker-compose up -d --build
           env:
              DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
              DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              DOCKER_TLS_VERIFY: ${{ secrets.DOCKER_TLS_VERIFY }}
