name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build and Deployment apis
        run: docker-compose build && docker-compose up -d

      - name: Build and Deployment frontend
        run: docker-compose -f frontend/docker-compose.yml build && docker-compose -f frontend/docker-compose.yml up -d

      - name: health check relation
        run: |
          sleep 5
          curl --fail http://localhost || (docker-compose logs --tail=100 && exit 1)
